services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontendContainer
    ports:
      - "8000:80"
    networks:
      - examenInternal
    depends_on:
     - backend
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backendContainer
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - examenInternal
  mysql:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: databaseContainer
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:80"
    volumes:
      - databaseVolume:/var/lib/mysql
    networks:
      - examenInternal
networks:
  examenInternal:

volumes:
  databaseVolume:                   